import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

export default function Home() {

  const author = process.env.NEXT_PUBLIC_PROJECT_NAME;

  return (
    <>
      <Head>
        <title>NextJS Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-5xl font-bold">NextJS Project</h1>
        <p className="font-bold">{author}</p>
      </div>
    </>
  )
}
